openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'HEALFORM'
  license:
    name: MIT
servers:
  - url: 'localhost:8080'
  - url: 'api.healform.de'
paths:
  /user/{email}/appointments:
    get:
      summary: 'Get all scheduled appointments by specific e-mail.'
      operationId: listAppointments
      tags:
        - user
      parameters:
        - name: email
          in: path
          description: E-Mail of the user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'Sample response: Details about a user by ID'
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
        tag:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []